name: reaxdb_dart
description: "The fastest NoSQL database for pure Dart. 21,000+ writes/sec, instant cache reads, built-in encryption. Zero native dependencies."
version: 1.4.0
homepage: https://github.com/dvillegastech/ReaxBD
repository: https://github.com/dvillegastech/ReaxBD
issue_tracker: https://github.com/dvillegastech/ReaxBD/issues

topics:
  - database
  - nosql
  - offline-first
  - storage
  - cache

false_secrets:
  - "*AKIAIOSFODNN7EXAMPLE*"

environment:
  sdk: ^3.7.2

dependencies:
  path: ^1.8.3
  crypto: ^3.0.3
  # PointyCastle for native AES-256 performance (not WASM compatible)
  pointycastle: ^3.9.1

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
